language: node_js
node_js: '4'
sudo: false
cache:
  directories:
  - './node_modules'
before_install:
- echo "npm@3.9 broke installs (w/ shrinkwrap?). revert this to @3 when fixed"
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
- npm install -g npm@3.8
- npm config set progress false
script:
- npm run lint
- npm run build
notifications:
  email: false
