language: node_js
node_js: '4'
sudo: false
cache:
  directories:
  - './node_modules'
before_script:
- npm install -g npm@3
- npm config set progress false
script:
- npm run lint
- npm run build
notifications:
  email: false
